"""
Automated Training Pipeline for Dynamic Aerial Tiling Datasets.

Reads slicing metadata (slicing_meta.json) and Ultralytics configuration (dataset.yaml)
from a sliced dataset directory, dynamically resolves tile dimensions (imgsz),
calculates VRAM-safe batch sizes to avoid CUDA OOM, and executes YOLO model training.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger("TrainPipeline")


def calculate_safe_batch_size(
    tile_size: int,
    device: str = "auto",
    total_vram_gb: Optional[float] = None,
    default_cpu_batch: int = 8,
) -> int:
    """
    Calculate safe batch size based on available VRAM and tile resolution
    to prevent CUDA Out-of-Memory (OOM) errors during training.

    Parameters
    ----------
    tile_size : int
        Input square resolution of tiles (e.g. 320, 416, 512, 640).
    device : str
        Target compute device ('auto', 'cpu', '0', 'cuda:0', etc.).
    total_vram_gb : Optional[float]
        Explicit total VRAM in GB. If None, queried dynamically from PyTorch if CUDA is active.
    default_cpu_batch : int
        Safe default batch size for CPU training.

    Returns
    -------
    int
        Safe batch size (power of 2 between 2 and 64).
    """
    dev_str = str(device).strip().lower()
    if dev_str in ("cpu", "-1") and total_vram_gb is None:
        return default_cpu_batch

    vram_gb = total_vram_gb
    if vram_gb is None:
        try:
            import torch

            if torch.cuda.is_available() and dev_str != "cpu":
                dev_idx = 0
                if dev_str.isdigit():
                    dev_idx = int(dev_str)
                elif dev_str.startswith("cuda:"):
                    try:
                        dev_idx = int(dev_str.split(":")[1])
                    except Exception:
                        dev_idx = 0
                props = torch.cuda.get_device_properties(dev_idx)
                vram_gb = props.total_memory / (1024**3)
            else:
                return default_cpu_batch
        except Exception as exc:
            logger.warning("Could not query GPU properties via PyTorch (%s). Falling back to CPU batch.", exc)
            return default_cpu_batch

    # Dedicated activation headroom: reserve ~1.5 GB for OS/PyTorch runtime/weights
    usable_vram = max(1.0, vram_gb - 1.5)

    # Estimated memory per sample scaled relative to 640x640 (~0.20 GB per sample)
    res_scale = (float(tile_size) / 640.0) ** 2
    mem_per_sample = max(0.04, 0.20 * res_scale)

    raw_batch = usable_vram / mem_per_sample

    # Snap down to the nearest standard power-of-2 batch size
    allowed_batches = [2, 4, 8, 16, 32, 64]
    safe_batch = allowed_batches[0]
    for b in allowed_batches:
        if b <= raw_batch:
            safe_batch = b

    logger.info(
        f"Calculated safe batch size: {safe_batch} (VRAM: {vram_gb:.1f} GB, Usable: {usable_vram:.1f} GB, "
        f"Tile size: {tile_size}px, Raw estimate: {raw_batch:.1f})"
    )
    return safe_batch


def run_train(
    data_dir: Union[str, Path],
    model: str = "yolo11s.pt",
    epochs: int = 50,
    batch: Union[str, int] = "auto",
    device: str = "auto",
    workers: Optional[int] = None,
    project: str = "runs/train",
    name: str = "aerial_yolo_train",
    save: bool = True,
    plots: bool = True,
    dry_run: bool = False,
    **extra_kwargs: Any,
) -> Dict[str, Any]:
    """
    Launch automated training pipeline using metadata generated by dataset_slicer.

    Parameters
    ----------
    data_dir : Union[str, Path]
        Path to sliced dataset folder containing dataset.yaml and slicing_meta.json.
    model : str
        Base pretrained model or yaml config (default: yolo11s.pt).
    epochs : int
        Number of training epochs (default: 50).
    batch : Union[str, int]
        Batch size, or 'auto' for dynamic safe batch sizing (default: auto).
    device : str
        Target compute device ('auto', 'cpu', '0', etc.) (default: auto).
    workers : Optional[int]
        Number of DataLoader workers. If None, defaults to min(8, cpu_count).
    project : str
        Directory to save training runs (default: runs/train).
    name : str
        Run name (default: aerial_yolo_train).
    save : bool
        Whether to save checkpoints (default: True).
    plots : bool
        Whether to generate training metric plots (default: True).
    dry_run : bool
        If True, validates configs and paths without executing model.train() (default: False).
    **extra_kwargs : Any
        Additional keyword arguments forwarded to model.train().

    Returns
    -------
    Dict[str, Any]
        Dictionary with status, config, and training outputs.
    """
    data_path = Path(data_dir).resolve()
    if not data_path.exists():
        raise FileNotFoundError(f"Dataset directory '{data_path}' does not exist.")

    yaml_file = data_path / "dataset.yaml"
    meta_file = data_path / "slicing_meta.json"

    if not yaml_file.exists():
        raise FileNotFoundError(
            f"Dataset configuration file not found: '{yaml_file}'. "
            "Please ensure dataset_slicer.py has processed this dataset directory."
        )

    if not meta_file.exists():
        raise FileNotFoundError(
            f"Slicing metadata file not found: '{meta_file}'. "
            "Please ensure dataset_slicer.py has generated slicing_meta.json."
        )

    # 1. Read slicing metadata
    with open(meta_file, "r", encoding="utf-8") as f:
        meta = json.load(f)

    tile_size = int(meta.get("tile_size", 512))

    # 2. Resolve compute device
    dev_str = str(device).strip()
    if dev_str.lower() == "auto":
        try:
            import torch

            resolved_device = "0" if torch.cuda.is_available() else "cpu"
        except ImportError:
            resolved_device = "cpu"
    else:
        resolved_device = dev_str

    # 3. Resolve batch size
    if isinstance(batch, str) and batch.strip().lower() == "auto":
        resolved_batch = calculate_safe_batch_size(
            tile_size=tile_size,
            device=resolved_device,
        )
    else:
        resolved_batch = int(batch)

    # 4. Resolve worker threads
    resolved_workers = workers if workers is not None else min(8, os.cpu_count() or 1)

    train_config: Dict[str, Any] = {
        "data": str(yaml_file),
        "epochs": int(epochs),
        "imgsz": int(tile_size),
        "batch": int(resolved_batch),
        "device": resolved_device,
        "workers": int(resolved_workers),
        "project": str(project),
        "name": str(name),
        "save": bool(save),
        "plots": bool(plots),
        **extra_kwargs,
    }

    logger.info(
        f"Loaded dataset config from '{yaml_file}' | tile_size={tile_size}px, "
        f"altitude={meta.get('altitude')}m, classes={meta.get('classes_count')}"
    )
    logger.info(
        f"Configured training: model='{model}', imgsz={tile_size}, batch={resolved_batch}, "
        f"device='{resolved_device}', epochs={epochs}"
    )

    if dry_run:
        logger.info("Dry-run mode active: validation succeeded, skipping actual training loop.")
        return {
            "status": "dry_run_success",
            "model": model,
            "config": train_config,
            "meta": meta,
        }

    from ultralytics import YOLO

    yolo_model = YOLO(model)
    results = yolo_model.train(**train_config)

    return {
        "status": "success",
        "model": model,
        "results": results,
        "config": train_config,
        "meta": meta,
    }


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Automated Training Pipeline for Dynamic Aerial Tiling Datasets"
    )
    parser.add_argument(
        "--data-dir",
        "-d",
        type=str,
        required=True,
        help="Path to sliced dataset directory containing dataset.yaml and slicing_meta.json",
    )
    parser.add_argument(
        "--model",
        "-m",
        type=str,
        default="yolo11s.pt",
        help="Pretrained YOLO model checkpoint or YAML architecture (default: yolo11s.pt)",
    )
    parser.add_argument(
        "--epochs",
        "-e",
        type=int,
        default=50,
        help="Total training epochs (default: 50)",
    )
    parser.add_argument(
        "--batch",
        "-b",
        type=str,
        default="auto",
        help="Batch size or 'auto' for dynamically calculated safe batch size (default: auto)",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        help="Target device ('auto', 'cpu', '0', etc.) (default: auto)",
    )
    parser.add_argument(
        "--workers",
        "-w",
        type=int,
        default=None,
        help="DataLoader worker processes (default: min(8, cpu_count))",
    )
    parser.add_argument(
        "--project",
        type=str,
        default="runs/train",
        help="Destination directory for runs (default: runs/train)",
    )
    parser.add_argument(
        "--name",
        type=str,
        default="aerial_yolo_train",
        help="Experiment name (default: aerial_yolo_train)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate parameters, configurations and paths without executing training loop",
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    args = parse_args(argv)
    try:
        res = run_train(
            data_dir=args.data_dir,
            model=args.model,
            epochs=args.epochs,
            batch=args.batch,
            device=args.device,
            workers=args.workers,
            project=args.project,
            name=args.name,
            dry_run=args.dry_run,
        )
        print(f"[SUCCESS] Training pipeline execution finished with status: {res.get('status')}")
        return 0
    except Exception as exc:
        logger.error("Training pipeline failed: %s", exc)
        print(f"[ERROR] Training pipeline failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())